//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ConfigRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a { &quot;schedule&quot; : [ { &quot;day&quot; : &quot;MO&quot;, &quot;timetable&quot; : [ { &quot;hrIni&quot; : 0, &quot;minIni&quot; : 1, &quot;hrFin&quot; : 9, &quot;minFin&quot; : 0, &quot;hrPay&quot; : 25 }, { &quot;hrIni&quot; : 9, &quot;minIni&quot; : 1, &quot;hrFin&quot; : 18, &quot;minFin&quot; : 0, &quot;hrPay&quot; : 15 }, { &quot;hrIni&quot; : 18, &quot;minIni&quot; : 1, &quot;hrFin&quot; : 24, &quot;minFin&quot; : 0, &quot;hrPay&quot; : 20 } ] }, { &quot;day&quot; : &quot;TU&quot;, &quot;timetable&quot; : [ { &quot;hrIni&quot; : 0, &quot;minIni&quot; : 1, &quot;hrFin&quot; : 9, &quot;minFin&quot; : 0, &quot;hrPay&quot; : 25 }, { &quot;hrIni&quot; : 9, &quot;minIni&quot; : 1, &quot;hrFin&quot; : 18, &quot;minFin&quot; : 0, &quot;hrPay&quot; : 15 }, { &quot;hrIni&quot; : 18, &quot;minIni&quot; : 1, &quot;hrFin&quot; : 24, &quot;minFin&quot; : 0, &quot;hrPa [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PaymentSchedule {
            get {
                return ResourceManager.GetString("PaymentSchedule", resourceCulture);
            }
        }
    }
}
